version: '3'

services:
  db:
    image: postgres:14.3
    restart: "no"
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: ${POSTGRES_CONTAINER_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
